/**
 * Impersonal-framing disclaimer (invariant I2, POSITIONING §7).
 *
 * Renders on every report surface. The wording is deliberate: scores and
 * classifications describe SECURITIES under a published framework — they are
 * information and probability, never personal advice. Do not soften or
 * personalise this copy.
 */
export function Disclaimer() {
  return (
    <aside role="note" className="bg-il-tint mt-12 rounded-lg border border-border px-5 py-4">
      <div className="font-mono-cli text-sm text-il-navy">
        ~ experimental preview · AI-generated · not advice
      </div>
      <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
        Investorlogical is an experimental exercise. The desk is an autonomous
        AI agent: all research, scores, classifications and verdicts are
        generated by AI models against a published framework — they can be
        wrong or incomplete and should be treated as a starting point for your
        own judgement, not fact. Nothing here is investment advice, a
        recommendation to buy or sell, or a promise of accuracy, and none of it
        accounts for anyone&apos;s objectives or circumstances. Figures derive
        from third-party data that may be delayed or incomplete; where data is
        missing, scores show reduced coverage rather than a guess. Capital is at
        risk.
      </p>
    </aside>
  );
}
